### PR TITLE
Update Handlebars version to 3.0.3

### PR DESCRIPTION
**Pull request by mucsi96**

### CODE REVIEW

**Comment by interlock** [comment]
Thanks, bumped version to be SEMVER with handlebars, so you will need to jump to ~3.0.0

**Comment by mucsi96** [comment]
Thanks, great! Amazing module!

**Comment by mucsi96** [comment]
Please publish it to npm

**Comment by interlock** [comment]
Ah shoot, forgot I had to run that. Used to having CI do that for me :-)

*done*

**Comment by mucsi96** [comment]
Thanks!

**Pull request merged**
